### ISSUE TITLE
Use new dropwizard metrics groupId

### ISSUE THREAD

**Issue by philsttr** [newrelic/dropwizard-metrics-newrelic#102]
## Is your feature request related to a problem? Please describe.

dropwizard-metrics-newrelic currently depends on the old `io.dropwizard` groupId for dropwizard metrics artifacts.

## Feature Description

Use the new `io.dropwizard.metrics` groupId for all dropwizard metrics dependencies, and upgrade to the latest dropwizard releases.

## Priority
Must Have

**Comment by kford-newrelic** [comment]
@philsttr thanks for submitting this issue - we will review this for one of our upcoming quarters but there is no guarantee that it will be prioritized. If you'd like to submit a PR, that would be greatly appreciated!

**Comment by kanderson250** [comment]
The dropwizard-newrelic-metrics reporter has been updated to use the most recent version of io.dropwizard as well as io.dropwizard.metrics in its dependencies.
- Latest: [ Release 1.0.0 ](https://github.com/newrelic/dropwizard-metrics-newrelic/releases/tag/v1.0.0)
- [ Release 0.9.0 ](https://github.com/newrelic/dropwizard-metrics-newrelic/releases/tag/v0.9.0)
