### ISSUE TITLE
Add custom internal "tag" to indicate dropwizard source

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/dropwizard-metrics-newrelic#22]
We should "tag" all metrics coming from the dropwizard exporter with a custom common attribute that indicates that the metric came from a dropwizard application.

There is a data model doc that describes the convention for tags.

`instrumentation.provider` should be set to "dropwizard"
`collector.name` should be set to "dropwizard-metrics-newrelic"

**Comment by jkwatson** [comment]
add `newRelic.metricSourceLibrary` attribute, maybe?
