### ISSUE TITLE
Improve getting-started documentation

### ISSUE THREAD

**Issue by jkwatson** [newrelic/dropwizard-metrics-newrelic#30]
We should at least mention that if you're using DropWizard the framework, that the `io.dropwizard.setup.Environment` instance has a reference to the metric registry that you can register the reporter with.

**Comment by breedx-nr** [comment]
Let's also provide a link from https://github.com/newrelic/dropwizard-metrics-newrelic to its exporter spec: https://github.com/newrelic/exporter-specs/tree/master/dropwizard Same for the other reporters.
