### ISSUE TITLE
Add exporter version information to the user agent string.

### ISSUE THREAD

**Issue by a-feld** [newrelic/dropwizard-metrics-newrelic#47]
See newrelic/newrelic-exporter-specs#22. The user agent for exporters should include the exporter name/language and the exporter version! This metadata may be used by customers to explore where their data is generated.

**Comment by kford-newrelic** [comment]
@a-feld this is a great suggestion but unfortunately we won't be able to prioritize this for our roadmap. We'll have to close this with no further action.
