### ISSUE TITLE
Dropwizard ReporterFactory

### ISSUE THREAD

**Issue by sschwell** [newrelic/dropwizard-metrics-newrelic#54]
Is there a io.dropwizard.metrics.ReporterFactory for this Reporter?
Would be nice to configure this in the dropwizard config file like other reporters.

**Comment by jkwatson** [comment]
Hi @sschwell ! Thanks for the suggestion. If you have the time to start working on it, we welcome contributions. Otherwise, we'll try to get to this as soon as we can.

**Comment by jkwatson** [comment]
@sschwell It looks like that interface is a part of dropwizard itself, rather than the metrics library, correct? We don't want this reporter to depend on the dropwizard framework, only the metrics library. I'm not sure where the `ReporterFactory` would live; perhaps in a contrib module? Do you have any thoughts on this?

**Comment by sschwell** [comment]
Yes, it is part of io.dropwizard:dropwizard-metrics. Looking at the way github.com/coursera/metrics-datadog handled it, they kept it in a separate maven module but did include it in the jar artifact. I think if the dependency is declared to be `implementation("io.dropwizard:dropwizard-metrics:2.0.5")` it does not force the dependency on consumers. I think.

**Comment by jkwatson** [comment]
That seems like a reasonable approach. Would you be interested in submitting a PR with it added?

**Comment by sschwell** [comment]
Sure. I will find time to work on it.
Another issue is how/if to allow choice of HttpPoster implementation in the dropwizard config file. AbstractHttpPosterFactory might do the trick.

**Comment by jkwatson** [comment]
cool. Yeah, being able to switch which http implementation to use would be very useful. I'll create a general issue to track it:  #55

**Comment by breedx-nr** [comment]
Fixed in #56
