### ISSUE TITLE
Make it easy to provide your own HttpPoster implementation

### ISSUE THREAD

**Issue by jkwatson** [newrelic/dropwizard-metrics-newrelic#55]
Or to switch it out with a java 11+ version, for example. Right now, you have to manually build your own `MetricBatchSender` out of the pieces. It would be nice to make it easy for the user to swap out the okHttp version for their own.

**Comment by sschwell** [comment]
This would seem to be a prereq for #54. right? What's the timing?

**Comment by jkwatson** [comment]
You could have a ReporterFactory that doesn't allow overriding the HttpPoster, and then add that feature after this one is complete.

**Comment by kford-newrelic** [comment]
Hi @jkwatson this is a great suggestion but unfortunately we're not able to prioritize this for our roadmap. We'll have to close this with no further action.
