### ISSUE TITLE
The TelemetryClient creates a thread pool which is never shut down

### ISSUE THREAD

**Issue by LigiaStefanaStan** [newrelic/dropwizard-metrics-newrelic#64]
Hello,

Thanks for all your hard work on this project, we find this library very useful and have been using this in several of our projects.

In one of our applications, we have a slightly unusual use-case in which the application needs to start and stop as required. We’ve noticed that in the latest library version 0.4.0 there are threads holding the client alive which prevent the JVM from exiting -- it looks like the TelemetryClient creates a thread pool which is never shut down.

To reproduce this issue, a test case has been provided here: https://github.com/LigiaStefanaStan/metrics-newrelic-example
If you run the example as it is, then the application will hang at shutdown. If you uncomment the lines in Application.java which shut down the TelemetryClient thread pool, then it will exit cleanly.

One idea we had for fixing this was to add a method to NewRelicReporterBuilder to allow us to specify our own TelemetryClient which we could then shut down ourselves. That seems like a low impact fix that is in line with the design, as the NewRelicReporterBuilder already provides methods for specifying other parameters. If that seems like a reasonable fix to you, then we’d be more than happy to create a pull request for the change, if it helps.

Thank you for your time and for all the efforts in building this metrics reporter -- highly appreciated.

Cheers,
Ligia Stan

**Comment by jkwatson** [comment]
Would the easy solution be for our reporter to override the `close()` method and shut down the TelemetryClient before calling `super.close()`?

**Comment by breedx-nr** [comment]
Hi @LigiaStefanaStan can you please try release 0.6.1 and see if this fixes your issue?

**Comment by breedx-nr** [comment]
Ok, let's try this again. :)
@LigiaStefanaStan we released 0.5.0 this morning, which contains both an explicit call to close() the TelemetryClient and also an update to the telemetry sdk 0.6.1 which contains a change to support daemon threads.  Would you be able to try that new version out and let us know if that resolves this problem?

Thanks in advance, and thanks for letting us know about this!

**Comment by LigiaStefanaStan** [comment]
Hi, @breedx-nr ! I have tried the new version and it does solve our problem! Thank you very much for the quick response and fix -- much appreciated!!

**Comment by breedx-nr** [comment]
Great news!  So glad it worked out, and thanks again for following up.
