### ISSUE TITLE
NoSuchMethodError when running from EMR

### ISSUE THREAD

**Issue by ckorakidis** [newrelic/dropwizard-metrics-newrelic#83]
I can send metrics when running locally, fails when running on an Amazon EMR:
Using 0.5.0
```
ERROR ApplicationMaster: User class threw exception: java.lang.NoSuchMethodError: com.codahale.metrics.ScheduledReporter.<init>(Lcom/codahale/metrics/MetricRegistry;Ljava/lang/String;Lcom/codahale/metrics/MetricFilter;Ljava/util/concurrent/TimeUnit;Ljava/util/concurrent/TimeUnit;Ljava/util/concurrent/ScheduledExecutorService;ZLjava/util/Set;)V
java.lang.NoSuchMethodError: com.codahale.metrics.ScheduledReporter.<init>(Lcom/codahale/metrics/MetricRegistry;Ljava/lang/String;Lcom/codahale/metrics/MetricFilter;Ljava/util/concurrent/TimeUnit;Ljava/util/concurrent/TimeUnit;Ljava/util/concurrent/ScheduledExecutorService;ZLjava/util/Set;)V
	at com.codahale.metrics.newrelic.NewRelicReporter.<init>(NewRelicReporter.java:82)
	at com.codahale.metrics.newrelic.NewRelicReporterBuilder.build(NewRelicReporterBuilder.java:95)
```

**Comment by ckorakidis** [comment]
Looks like there is overlapping with previous versions of metrics-core:

```
file:/mnt/yarn/usercache/hadoop/filecache/17/__spark_libs__6857221342199806521.zip/metrics-core-3.1.5.jar overlaps with 
file:/usr/lib/hadoop-mapreduce/metrics-core-3.0.1.jar - total overlapping classes: 79 - same classloader ! This is an ERROR!
...
...
...
>> jHades printResourcePath >> searching for com/codahale/metrics/ScheduledReporter.class

All versions:

jar:file:/mnt/yarn/usercache/hadoop/filecache/17/__spark_libs__6857221342199806521.zip/metrics-core-3.1.5.jar!/com/codahale/metrics/ScheduledReporter.class
jar:file:/usr/lib/hadoop-mapreduce/metrics-core-3.0.1.jar!/com/codahale/metrics/ScheduledReporter.class
jar:file:/mnt/yarn/usercache/hadoop/appcache/application_1602927091678_0003/container_1602927091678_0003_01_000001/__app__.jar!/com/codahale/metrics/ScheduledReporter.class

Current version being used: 

jar:file:/mnt/yarn/usercache/hadoop/filecache/17/__spark_libs__6857221342199806521.zip/metrics-core-3.1.5.jar!/com/codahale/metrics/ScheduledReporter.class

```

**Comment by breedx-nr** [comment]
Hi @ckorakidis.

Any new updates on this?  It looks like there are two version of `metrics-core` in the classpath. Any thoughts on why?  Is it a packaging/deploy issue?  

I wouldn't think that the New Relic reporter would be causing this...

**Comment by ckorakidis** [comment]
NewRelic is using metrics-core 4.1.5 while other products in EMR (e.g. hadoop) use older versions of EMR (3.0.1, 3.1.5 etc)
I preferred not to deal with the classpath so to avoid causing issues in existing stuff, so I finally resolved it by shading the metrics-core packages in the jar I provide when running the job

**Comment by breedx-nr** [comment]
Thanks @ckorakidis for the update.
We don't have a lot of experience deploying this to EMR, so it's good to hear that you got this working.  Is the older version of `metrics-core` a limitation of something that's part of EMR, or maybe something that's specific to your build/deploy pipeline?  

I like that shading worked...but I'm wondering if something we should provide additional documentation around.  If so, does this sound like something you might help with?

**Comment by ckorakidis** [comment]
@breedx-nr older versions are used in other components in EMR (e.g. hadoop) which are part of the EMR setup, not my software.

What I did to be able to use the `metrics-core 4.1.5` in my application, was to update the build.sbt by setting the shading in the application of the jar which is deployed in the EMR:

`
assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("com.codahale.metrics.**" -> "com.my.company.shaded.codahale.metrics.@1")
    .inLibrary("io.dropwizard.metrics" % "metrics-core" % "4.1.5")
    .inAll
)`

I hope that helps.

**Comment by kford-newrelic** [comment]
Reviewed and determined to be permanently deferred.
