### ISSUE TITLE
Update to latest SDK

### ISSUE THREAD

**Issue by mschechter-bellese** [newrelic/dropwizard-metrics-newrelic#90]
Please update this library to the latest [Telemetry SDK](https://github.com/newrelic/newrelic-telemetry-sdk-java); the version in use is over a year out of date.

**Comment by mschechter-bellese** [comment]
@kford-newrelic,

A couple of questions:
1. Is this something you'd be interested in a pull request on?
2. Does updating the Telemetry SDK change how data is sent to New Relic and displayed on the dashboard? Teams using the Micrometer integration have their data show up as "OpenTelemetry Services"
3. Is there a way to change to FedRAMP-compliant endpoints for publishing the data?

Thanks!

**Comment by jasonjkeller** [comment]
Hey @mschechter-bellese 👋 

1. Yes! PRs are always welcome and encouraged!
2. Updating the TelemetrySDK won't effect the entity type generated by this DropWizard metrics reporter in NROne. It will continue to report as a `Services - OpenTelemetry` entity. I believe an agent run ID is what causes APM agents to report as `Services - APM` entity types. Data from other integrations/reporters/exporters gets reported as `Services - OpenTelemetry` entity types.
3. I haven’t tested with a FedRAMP endpoint but I believe that the `overrideUri` config mentioned [here](https://github.com/newrelic/dropwizard-metrics-newrelic#dropwizard-metrics-reporter) can be used to change the metric ingest endpoint to whatever you want.
